### ISSUE TITLE
Same options from two different places 

### ISSUE THREAD

**Issue by Gauravjeetsingh** [inderpreetsingh/brl-cad-wiki#26]
On resolution of 1024 X 768 I get a left sidebar with few options, and some tools near search button.
On clicking the third icon from left of searchbar, I get the same options which I have on my left sidebar.

![glitch](https://f.cloud.github.com/assets/1990932/2247841/7b7488e2-9d72-11e3-8fab-ca31845c7535.png)

**Comment by inderpreetsingh** [comment]
Duplicate of issue #20 , you explained it better though!
